### PR TITLE
Array methods

### PR DESCRIPTION
**Pull request by CatherineNjenga**
Submitting array methods assignment for review.

### CODE REVIEW

**Comment by jdevries3133** [comment]
On format names line 20, can you compare your solution to the provided solution? Identify the strengths & weakness of each? And think of some names that would be rejected by the provided solution but accepted by yours? Finally, which solution do you think is best?

**Comment by jdevries3133** [comment]
On format names line 20, can you compare your solution to the provided solution? Identify the strengths & weakness of each? And think of some names that would be rejected by the provided solution but accepted by yours? Finally, which solution do you think is best?

In "names to title case" you have a mutative loop inside your map callback. Can you replace the inner loop with an inner map? Remember, this is a map use-case! You're transforming every letter!

**Comment by jdevries3133** [comment]
Looks good! Now take some time to review the solutions that were there initially and let me know if you have any questions in that process.

**Comment by CatherineNjenga** [comment]
On the challenge on formatting names, I prefer the provided solution. In my solution, using .split(' ') is limited to the pattern passed as an argument, therefore names that may require a different pattern will not pass the test(s).

**Comment by CatherineNjenga** [comment]
Yes, the use of loops inside the iterative array methods instead of using the iterative array methods themselves sine they have 'built-in' loops. Thank for your insight.

**Comment by CatherineNjenga** [comment]
I have a question on the formatted names. Incase one is not conversant with regular expressions, can one derive an optimal working solution for names that may need to be filtered using more than one pattern?

**Comment by jdevries3133** [comment]
> I have a question on the formatted names. Incase one is not conversant with regular expressions, can one derive an optimal working solution for names that may need to be filtered using more than one pattern?

Hey sorry for the late reply. Regexes just take practice, like anything else! There are interactive websites that help you visualize and debug regexes, which allows pretty much anyone to write quite complicated regular expressions. Ultimately, there are definitely a wide range of string manipulation problems that are most easily solved with regular expressions, and some that would require a ton of fiddly code to solve any other way.

**Pull request merged**
